project:
  name: go-web-build
  version: 1.0.0
environment: production
server:
  port: 8080
  host: 0.0.0.0
  dev_mode: false
build:
  out_dir: dist
  source_map: false
  minify: true
  cache: true
  cache_dir: .cache
  assets:
    images: assets/images
templates:
  directory: templates
  cache: true