image: node:18-alpine

stages:
  - test
  - build
  - deploy

variables:
  NPM_TOKEN: ${CI_NPM_TOKEN}

cache:
  paths:
    - node_modules/

test:
  stage: test
  script:
    - npm ci
    - npm run test
    - npm run lint
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/

build:
  stage: build
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - build/

deploy:
  stage: deploy
  script:
    - echo "Deploying application..."
  environment:
    name: production
  only:
    - main