name: Release CI/CD Pipeline with docs
on:
  push:
    branches: [ master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ master ]

jobs:
  docs:
      needs: [release]
      runs-on: ubuntu-latest
      if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')
      steps:
        - uses: actions/checkout@v3

        - name: Setup Node.js
          uses: actions/setup-node@v3
          with:
            node-version: '18'

        - name: Install Docsify CLI
          run: npm i docsify-cli -g

        - name: Build Documentation
          run: |
            cd docs
            docsify serve . &
            sleep 5
            curl http://localhost:3000 > index.html

        - name: Deploy to GitHub Pages
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./docs
            force_orphan: true