name: Documentation Pipeline
on:
  push:
    branches: [ master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ master ]

jobs:
  docs:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './docs/package.json'

      - name: Install dependencies
        working-directory: ./docs
        run: |
          npm install
          npm install docsify-cli@latest -g

      - name: Setup documentation
        working-directory: ./docs
        run: |
          if [ ! -f "index.html" ]; then
            docsify init .
          fi
          
          # Update version in docs
          VERSION=$(git describe --tags --always --dirty)
          echo "Current version: $VERSION" >> _sidebar.md

      - name: Generate documentation
        working-directory: ./docs
        run: |
          npx docsify-cli serve . --port 3000 &
          sleep 3
          curl -s http://localhost:3000
          pkill -f "docsify-cli serve"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          force_orphan: true
          commit_message: 'docs: update documentation [skip ci]'
          enable_jekyll: false
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'