name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true
      
      - name: Build
        run: |
          mkdir -p build
          go build -o build/gobuild ./cmd/gobuild
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build/
          retention-days: 5

  release:
    needs: [build]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: build
      
      - name: Set executable permissions
        run: chmod +x build/gobuild
      
      - name: Create Release Archive
        run: |
          tar -czf gobuild-${{ github.ref_name }}.tar.gz -C build gobuild
          zip -j gobuild-${{ github.ref_name }}.zip build/gobuild

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            gobuild-${{ github.ref_name }}.tar.gz
            gobuild-${{ github.ref_name }}.zip
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  